
export const metadata = {
  title: "Ahmed Next App",
  description: "Generated by create next app",
 
};

export default function home ({children}){
    return (
        <div>
            {children}
        </div>
    )
}